### ISSUE TITLE
Fixing test-queue.cpp

### ISSUE THREAD

**Issue by EricXuZh** [rpharrigan211/cs4500-assignment1-part2#3]
In test-queue.cpp, on line 46 strmp() takes in two char*'s, but you have provided to String*'s. Additionally, for test-queue.cpp, you have to import <stdio.h> if you want to use printf. And there are some places where you're using '.' instead of '->' to access methods, such as in 'queue1.add' on line 50 (there are other places as well, this is just one).

**Comment by mike-eiden** [comment]
I can confirm that these are issues.  I have opened PR #4 to try to address some of the more basic ones, but some require more design decisions.  I would propose that instead of using cstring classes for tests we use the local string.h equals function.  However, if this is not the decided upon design just please ensure that test-queue.cpp compiles.  Thanks!

**Comment by rpharrigan211** [comment]
Merged and fixed!
